# Generated by Django 5.1.3 on 2024-11-09 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExcelData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('process_id', models.CharField(max_length=255)),
                ('cg_pno', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('rank', models.CharField(max_length=255)),
                ('unit_descriptions', models.CharField(max_length=255)),
                ('batch', models.CharField(max_length=255)),
                ('uploaded_on', models.DateField()),
                ('user_name', models.CharField(max_length=255)),
                ('process_name', models.CharField(max_length=255)),
                ('form_no', models.CharField(max_length=255)),
                ('refrence_type', models.CharField(max_length=255)),
                ('form_type', models.CharField(max_length=255)),
                ('from_date', models.DateField()),
                ('allocated_on', models.DateField()),
                ('task_to', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=255)),
                ('stage', models.CharField(max_length=255)),
                ('approver_remarks', models.TextField()),
                ('verifier_remarks', models.TextField()),
                ('initiator_remarks', models.TextField()),
                ('update_date', models.DateField()),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
