# Generated by Django 5.1.3 on 2024-11-19 03:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('self_service', '0008_userquery_user_alter_userquery_category_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userquery',
            old_name='title',
            new_name='pf_no',
        ),
        migrations.RenameField(
            model_name='userquery',
            old_name='category',
            new_name='pf_unit',
        ),
    ]
