# Generated by Django 5.1.3 on 2024-11-19 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('self_service', '0009_rename_title_userquery_pf_no_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='email',
        ),
        migrations.AddField(
            model_name='feedback',
            name='subject',
            field=models.TextField(default=5),
            preserve_default=False,
        ),
    ]
