# Generated by Django 5.1.3 on 2024-11-19 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('self_service', '0010_remove_feedback_email_feedback_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='subject',
            field=models.CharField(max_length=100),
        ),
    ]
